name: yoyo_web_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  awesome_snackbar_content: ^0.1.8
  csv: ^6.0.0
  desktop_drop: ^0.7.0
  excel: ^4.0.2
  file_picker: ^10.3.3
  file_saver: ^0.3.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^9.0.0
  go_router: ^16.3.0
  google_fonts: ^7.0.2
  http: ^1.6.0
  intl: ^0.20.0
  just_audio: ^0.10.5
  pdf: ^3.10.4
  pin_code_fields: ^8.0.1
  printing: ^5.11.0
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.3
  web: ^1.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  generate: true
